### ISSUE TITLE
AB通道的UUID似乎标反了

### ISSUE THREAD

**Issue by GreckF** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#11]
如题。

**Comment by zeiyu314** [comment]
您好可以提供任何一种编程语言的示例代码吗？我不是很理解文档的内容。

**Comment by DG-LAB-OPENSOURCE** [comment]
@GreckF 也许是这样，您根据实际情况来使用，感谢您的支持
@zeiyu314  您好，我们目前只开源了部分蓝牙协议，和socket控制玩法协议，感谢您的支持
