### ISSUE TITLE
Can you improve the AI-Mode, please? / 请问可以改进一下AI模式吗？

### ISSUE THREAD

**Issue by T-Wittich** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#12]
Currently, AI mode can only amplify the signal over time. Once the signal has reached its upper limit, it will remain at that strength even if the whole thing starts over again after a pause.

It would be nice if this increase could be reset after each break as an option in AI mode. So the game reaches a maximum but starts over after the break.

---

目前，AI模式只能随时间放大信号。 一旦信号达到上限，即使整个过程在暂停后重新开始，它也会保持该强度。

如果这种增加可以在每次休息后重置作为人工智能模式的一个选项，那就太好了。 因此游戏达到最大值，但在休息后重新开始。

**Comment by DG-LAB-OPENSOURCE** [comment]
Thank you for your suggestion. We will include your proposal in our discussion agenda

**Comment by DG-LAB-OPENSOURCE** [comment]
您描述的整个过程在暂停后，是指什么，希望您能进一步描述一下

**Comment by Vpn33** [comment]
我理解的意思就是能自动重置强度设置，重新一轮循环。感觉就是我之前和DG官方提到的【电源管理】功能。【智能强度】这个现在模式有点单一还只能手动每次调节，希望电源强度能像波形一样，通过自定义的方式来自动的进行电源大小的管理。(不过现在有SOCKET模式了，这个功能现在也能通过socket实现了，笑～ 给官方的socket控制点赞，终于能把之前做不了的功能给补上了，开心～)
以下是我去年根据旧的V2做的【电源管理】，希望官方可以参考下。
![image](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/assets/86939278/ff174b5e-425e-4052-87d5-9448e7fcb3a9)
![image](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/assets/86939278/0a0a5653-8852-4e86-a767-0421ade1ef75)

另外还有当时我做的【智能强度】，和官方的意思不一样，我这个是根据用户习惯自动调节电源强度的，因为有时候不同波形的切换时即使相同强度也会产生较强的冲击(现在的V3平衡参数可以按通道分开设置，情况比V2好很多很多，至少我目前还没有遇到太强烈的冲击，从V3到手到现在都没再用自己写的那个基于V2的客户端了，不过还是希望为官方能提供些参考)
![image](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/assets/86939278/a010391a-83ef-4986-8cfa-2ef4fd2eb881)
![image](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/assets/86939278/57eb4c4e-1301-4b09-bcc7-b63a04ee23bd)

**Comment by DG-LAB-OPENSOURCE** [comment]
非常感谢您对DG-LAB的喜爱与支持
