### ISSUE TITLE
0x180B的服务中貌似还存在0x1507的特性

### ISSUE THREAD

**Issue by RayShark0605** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#13]
我编译并且仔细分析了`https://github.com/OpenDGLab/OpenDGLab-Desktop`的代码，发现其中的`Global::DGLabServices::EStimStatus::Characteristic::setup`特性是0x1507，而且能正确读取，请问能否告知0x180B的服务中的0x1507特性的含义和功能？

**Comment by DG-LAB-OPENSOURCE** [comment]
1507表示向脉冲主机输入的通道强度范围和步长。强度范围固定值 = 2000，步长在3.0的APP中设置的是10，所以3.0中希望强度显示为25时，输入的强度值 = 25 * 10；另外脉冲主机notify回来的强度值也需要经过计算，若饭回来1640，则显示在3.0APP中的强度值就是 = 1640 / 10 = 164。而且APP中显示的最大强度值 = 2000 / 10 = 200。所以可以通过1507中修改步长值来修改你的程序中强度增减的粒度。
