### ISSUE TITLE
新的V3协议比原来V2复杂了好多，能否提供些SDK以供调用？

### ISSUE THREAD

**Issue by xudl33** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#16]
使用v2的协议时，就有过把AB波形合并来提高效率的想法，没想到V3还真这么干了,给官方点赞！不过自己实现的波形编辑器有点复杂，现在V3的参数又变多了，除了高低频平衡，还多了播放速率，相对强度啥的，而且波形图像算法和协议返回值都变化了，感觉还是官方出个能迭代的SDK更好，改接口总全比重构要容易的多啊。出个JAVA、python、JS、NodeJS的SDK现在都能跨平台，比协议更容易集成。

**Comment by klxf** [comment]
之前问过说会提供官方接口可以直连第三方服务器，晚点会更新详细信息🤔

**Comment by DG-LAB-OPENSOURCE** [comment]
3.2.0 应用上线了SOCKET控制功能，在本项目中开源了我们的示例代码和协议文档，您可以参考一下

**Comment by xudl33** [comment]
> 3.2.0 应用上线了SOCKET控制功能，在本项目中开源了我们的示例代码和协议文档，您可以参考一下
诶呀，这个必须大大的赞一下！下来研究下。

**Comment by ltx4jay** [comment]
I have created a convenience API that abstracts the details of the BLE protocol.

It's currently only V2 but I will be adding V3 support shortly, once I have received my unit.

https://github.com/ltx4jay/NimBLE-Devices/blob/main/include/NimBLE-Device/Coyote.hh
