### ISSUE TITLE
Questions on V3 protocol waveform data

### ISSUE THREAD

**Issue by ltx4jay** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#18]
I'm reading the specification through Google Translate and I really like this new version of the protocol. There are however two aspects that are not clear. 

1. What is the unit of the 10..240 waveform frequency length and how does it relate to the 25ms output window? The [conversion algorithm](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/blob/main/image/README_V3.md#%E9%80%9A%E9%81%93%E6%B3%A2%E5%BD%A2%E9%A2%91%E7%8E%87%E9%80%9A%E9%81%93%E6%B3%A2%E5%BD%A2%E5%BC%BA%E5%BA%A6) seem to imply that is it not linear with regions going from 10..100, 101..199, and 201..240.

2. What are the units of the 0..100 waveform intensity?

3. Can you give examples for generating "medium" intensity waveforms with 1Hz, 10Hz, and 40Hz pulses, as well as absolute maximum frequency?

4. Is there a way to translate or map (even loosely) V2 waveform data to V3 waveform data?

**Comment by DG-LAB-OPENSOURCE** [comment]
Thank you very much for your support and love of DG-LAB. In response to your question, we have updated the document and hope to solve your problem

**Comment by ltx4jay** [comment]
Putting a link here to the extra information that was just added for posterity:

[coyote/extra/README.md](https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/blob/main/coyote/extra/README.md)

Thank you!
