### ISSUE TITLE
如何判断蓝牙设备是否为郊狼

### ISSUE THREAD

**Issue by MossCG** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#22]
如题
郊狼是否有固定的蓝牙地址或蓝牙名称一类的4
可以用于判断是否为郊狼设备
如果每个设备都要连一遍获取服务UUID的话太费时间了

**Comment by DG-LAB-OPENSOURCE** [comment]
通过蓝牙名称来区分：
1. 郊狼脉冲主机 3.0 的蓝牙名称为：47L121000
2. 郊狼脉冲主机 2.0 的蓝牙名称为：D-LAB ESTIM01
3. 按钮传感器 的蓝牙名称为：47L120100

**Comment by MossCG** [comment]
草，我还以为要判断服务uuid什么的，原来这么简单（（（（（

**Comment by MossCG** [comment]
建议写到蓝牙协议的文档里面

**Comment by DG-LAB-OPENSOURCE** [comment]
文档已更新
