### ISSUE TITLE
V3蓝牙协议Write with Response

### ISSUE THREAD

**Issue by MossCG** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#27]
如题，在使用bleak进行v3版本蓝牙开发时遇到一个问题
0x150A是必须Write with Response吗？
在开发v2的时候只需要：client.write_gatt_char(strengthUUID, bytes(command))
而开发v3的时候使用v2的方法会报错/OSERROR参数错误，需要：client.write_gatt_char(strengthUUID, bytes(command), response=True)

但是使用v3方法也写不进去，v3主机是否需要初始化一类的操作？
附上代码：
`
async def setStrength(channelA, channelB):
    strengthUUID = "0000150A-0000-1000-8000-00805f9b34fb"
    sequenceNumber = 0x01
    strengthParsingMethod = 0b1111
    command = bytearray([0xB0, sequenceNumber, strengthParsingMethod])
    command.append(int(channelA))
    command.append(int(channelB))
    command.append(int(channelA))
    command.extend([0x00] * 16)
    result = await BasicData.client.write_gatt_char(strengthUUID, bytes(command), response=True)
    BasicIO.output_command("event", "updateStrength " + str(channelA) + " " + str(channelB))
`

**Comment by DG-LAB-OPENSOURCE** [comment]
所有写入都是with no response，V3主机暂无需要初始化的操作
