### ISSUE TITLE
请求添加v3主机蓝牙协议BE消息的示例

### ISSUE THREAD

**Issue by shilapi** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#28]
如题
https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE/blob/main/coyote/v3/README_V3.md

**Comment by DG-LAB-OPENSOURCE** [comment]
BE消息是 通过 150B 特性 NOTIFY 传回的，与您写入的 BF消息一致。表示您已向设备成功写入了对应的设置
