### ISSUE TITLE
International version of web demo page

### ISSUE THREAD

**Issue by IvSan** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#30]
Hello!
Is English version of `coyote`-`web`-`bluetooth.html` expected? Would you like to have some help with translation?

**Comment by DG-LAB-OPENSOURCE** [comment]
Do you mean you want an English version of the text and comments in bluetooth.html？

**Comment by IvSan** [comment]
Yep

**Comment by DG-LAB-OPENSOURCE** [comment]
Just a moment, I'll make an update

**Comment by DG-LAB-OPENSOURCE** [comment]
Project updated

**Comment by IvSan** [comment]
Amazing! Thank you!

**Comment by IvSan** [comment]
Can I also ask for some help please?  
I am looking into protocol version `v2`, I have figured out what are bytes `[X,Y,Z]` doing.
In the README file there is a line: `两个单极性脉冲的高度(电压)由这个通道的强度决定` = `The height (voltage) of the two unipolar pulses is determined by the strength of this channel`. However I cannot find in the `bluetooth.html` how do you control the channel strength.  
Can you please guide me how to control the channel strength from the browser?

**Comment by DG-LAB-OPENSOURCE** [comment]
We only provide Bluetooth connection and pulse writing for suburban wolf devices for this function, and have not yet provided channel strength settings. You can manually adjust the strength by turning the device's dial. If you want to adjust the strength, we provide the Bluetooth characteristic for strength settings in the V2 protocol document(PWM_AB2), and you can write your own code.

**Comment by IvSan** [comment]
Ok, got you, thanks.
