### ISSUE TITLE
让前端协议AB通道波形和interval也独立

### ISSUE THREAD

**Issue by ziniuguo** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#31]
您好

波形数据:

后端代码中默认波形数据发送间隔为200ms，您可以根据您的波形数据来调整后端的波形数据发送间隔(修改后端代码 timeSpace 的变量值)

type : clientMsg 固定不变

message : A通道波形数据(16进制HEX数组json,具体见上面的协议说明)

message2 : B通道波形数据(16进制HEX数组json,具体见上面的协议说明)

time1 : A通道波形数据持续发送时长

time2 : B通道波形数据持续发送时长

clientId: 终端ID

targetId: APP ID

现在这一部分只能两个通道波形数据一起设置，这样的话如果用户要单独只改一个通道就比较困难，重新发送波形数据信息就会影响到另一个。后端现在是分开的，前端也分开是不是更好？

如果您觉得有必要的话我可以改完开个PR

**Comment by DG-LAB-OPENSOURCE** [comment]
项目已更新
