### ISSUE TITLE
请问APP中的小节时长是如何计算的？

### ISSUE THREAD

**Issue by Vpn33** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#32]
如题，我看app上的滑动距离并不是均匀变化的， 想请问 APP的滑块值从1-100是如何变化成小节时长0.1-10.00的，公式是怎么样的？

**Comment by DG-LAB-OPENSOURCE** [comment]
对于脉冲形状，一个竖直滑块代表0.1秒的输出，在我们的程序中，每个小节都必须完整输出才会切到下一个小节。假设您当前小节的脉冲形状的滑块数量是8个，代表了0.8秒输出，小节时长设置为2.2秒，那么此时该小节循环了2次之后，小节时长还剩余 2.2 - 2*0.8 = 0.6秒，那么小节会继续再次完整输出一次，也就是小节时长里括号内的时长(3*0.8=2.4秒)，而2.4秒才是该小节输出的真实时长。举另外一个例子，假设您当前小节的脉冲形状滑块数量是10个，代表了1秒输出，小节时长设置3秒，那么此时该小节可以在小节时长内完整的循环3次，所以此时小节时长和该小节输出的真实时长是一样的(3 * 1.0=3.0秒)
