### ISSUE TITLE
No bluetooth protocol of the button sensor 47L120100

### ISSUE THREAD

**Issue by jlatex** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#33]
Please consider documenting the protocol of the button so we can use them in our own controller apps

**Comment by DG-LAB-OPENSOURCE** [comment]
The current Bluetooth protocol of button is not the final version and may require iterative updates in the future. We will consider whether to open source the Bluetooth protocol or integrate the button into the socket control function after the Bluetooth protocol is stable

**Comment by jlatex** [comment]
thank you. I hope you are willing to explain the protocol to talk to the buttons directly (not via the powerbox)

**Comment by jlatex** [comment]
We worked out how to use it, temporarily until you publish docs
