### ISSUE TITLE
為什麼用筆記本藍牙很難或者說無法連接到設備

### ISSUE THREAD

**Issue by lq821231** [DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE#6]
通過筆記本搜索藍牙，偶爾能找到D-LAB ESTIM01設備，但無法鏈接，更多的時候是找不到該設備。
我原計劃使用電腦瀏覽器通過xtoys.app進行操作，但是在藍牙上就無法找到該設備，請問有沒有什麼好的解決辦法？

**Comment by DG-LAB-OPENSOURCE** [comment]
設備需要以低功耗藍牙嘅形式連接，並非以經典藍牙形式
